#define ANASTASIACHAN_X 45
#define ANASTASIACHAN_Y 85
#define VENTANA_TAM_X   818
#define VENTANA_TAM_Y   475

#define ANASTASIA_MAX_TRAJES     3
#define ANASTASIA_MAX_ACCESORIOS 3
#define ANASTASIA_MAX_OJOS       4
#define ANASTASIA_MAX_BOCAS      7
#define ANASTASIA_MAX_CABEZAS    1
#define ANASTASIA_MAX_FONDOS     1
#define ANASTASIA_MAX_ICONS      1
#define ANASTASIA_MAX_BRAZOS     5
#define ANASTASIA_MAX_PIERNAS    2
#define ANASTASIA_MAX_TXT        2
